SELECT COUNT(*) AS TOTAL_EMPLOYEES
FROM EMPLOYEE1;

SELECT COUNT(*) AS TOTAL_PROJECTS
FROM PROJECT1;

SELECT COUNT(*) AS TOTAL_ASSIGNMENTS
FROM EMP_PROJ1;

SELECT AVG(Salary) AS AVERAGE_SALARY
FROM EMPLOYEE1;

SELECT MAX(Salary) AS Max_Salary,
MIN(Salary) AS Min_Salary
FROM EMPLOYEE1;

SELECT SUM(Salary) AS TOTAL_SALARY
FROM EMPLOYEE1;

SELECT AVG(Bonus) AS AVERAGE_BONUS
FROM EMPLOYEE1;

SELECT SUM(Comm) AS TOTAL_COMMISSION
FROM EMPLOYEE1;

SELECT COUNT(*) AS TOTAL_EMPLOYEES
FROM EMPLOYEE1
WHERE Salary > 30000;

SELECT COUNT(*) AS TOTAL_EMPLOYEES
FROM EMPLOYEE1
WHERE DeptNo = 'D11';

SELECT MAX(Bonus) AS HIGHEST_BONUS
FROM EMPLOYEE1;

SELECT MIN(Comm) AS LOWEST_COMMISSION
FROM EMPLOYEE1;



SELECT AVG(Salary) AS AVERAGE_SALARY
FROM EMPLOYEE1
WHERE Gender = 'F';

SELECT COUNT(*) AS TOTAL_MANAGERS
FROM EMPLOYEE1
WHERE Job = 'MANAGER';

SELECT MIN(StDate) AS EARLIEST_START_DATE
FROM PROJECT1;

SELECT MAX(EndDate) AS LATEST_END_DATE
FROM PROJECT1;

SELECT SUM(Salary) AS TOTAL_SALARY,
SUM(Bonus) AS TOTAL_BONUS,
SUM(Comm) AS TOTAL_COMMISSION
FROM EMPLOYEE1;

SELECT COUNT(*) AS TOTAL_EMPLOYEES
FROM EMPLOYEE1
WHERE Hire_Date > TO_DATE('01-JAN-2018','DD-MON-YYYY');

SELECT AVG(Salary) AS AVERAGE_SALARY
FROM EMPLOYEE1
WHERE Hire_Date > TO_DATE('01-JAN-2015','DD-MON-YYYY');

SELECT COUNT(DISTINCT DeptNo) AS TOTAL_DEPARTMENTS
FROM EMPLOYEE1;

CREATE TABLE EXTRA_WORK_EMP
(
 EmpNo    VARCHAR2(10),
EmpName  VARCHAR2(30),
   Gender   CHAR(1),
    Salary   NUMBER(10,2));
INSERT INTO EXTRA_WORK_EMP VALUES ('E0001','John','M',45000);
INSERT INTO EXTRA_WORK_EMP VALUES ('E0005','Anu','F',38000);
INSERT INTO EXTRA_WORK_EMP VALUES ('E0200','Rahul','M',30000);
               INSERT INTO EXTRA_WORK_EMP VALUES ('E0201','Meera','F',35000);
SELECT EmpName
FROM EMPLOYEE1
UNION
SELECT EmpName
FROM EXTRA_WORK_EMP;

SELECT EmpName
FROM EMPLOYEE1
UNION ALL
SELECT EmpName
FROM EXTRA_WORK_EMP;

SELECT EmpNo,EmpName
FROM EMPLOYEE1
INTERSECT
SELECT EmpNo,EmpName
FROM EXTRA_WORK_EMP;

SELECT EmpName
FROM EMPLOYEE1
MINUS
SELECT EmpName
FROM EXTRA_WORK_EMP;

SELECT EmpName
FROM EXTRA_WORK_EMP
MINUS
SELECT EmpName
FROM EMPLOYEE1;

ALTER TABLE EXTRA_WORK_EMP
ADD DeptNo VARCHAR2(10);

UPDATE EXTRA_WORK_EMP
SET DeptNo = 'D11'
WHERE EmpNo = 'E0001';

SELECT DeptNo
FROM EMPLOYEE1
UNION
SELECT DeptNo
FROM EXTRA_WORK_EMP;




SELECT DeptNo
FROM EMPLOYEE1
INTERSECT
SELECT DeptNo
FROM EXTRA_WORK_EMP;

SELECT DeptNo
FROM EMPLOYEE1
MINUS
SELECT DeptNo
FROM EXTRA_WORK_EMP;

SELECT EmpNo
FROM EMPLOYEE1
UNION ALL
SELECT EmpNo
FROM EXTRA_WORK_EMP;

SELECT EmpNo
FROM EMPLOYEE1
MINUS
SELECT EmpNo
FROM EXTRA_WORK_EMP;

SELECT DeptNo,
 SUM(Salary) AS TOTAL_SALARY
FROM EMPLOYEE1
GROUP BY DeptNo;

SELECT DeptNo,
AVG(Salary) AS AVERAGE_SALARY
FROM EMPLOYEE1
GROUP BY DeptNo;

SELECT DeptNo,
COUNT(EmpNo) AS NO_OF_EMPLOYEES
FROM EMPLOYEE1
GROUP BY DeptNo;

SELECT Job,
COUNT(EmpNo) AS NO_OF_EMPLOYEES
FROM EMPLOYEE1
GROUP BY Job;
SELECT Gender,
ROUND(AVG(Salary), 2) AS AVERAGE_SALARY
FROM EMPLOYEE1
GROUP BY Gender;

SELECT EdLevel,
COUNT(EmpNo) AS NO_OF_EMPLOYEES
FROM EMPLOYEE1
GROUP BY EdLevel;

SELECT DeptNo,
SUM(Bonus) AS TOTAL_BONUS
FROM EMPLOYEE1
GROUP BY DeptNo;

SELECT RespEmp,
COUNT(ProjNo) AS NO_OF_PROJECTS
FROM PROJECT1
GROUP BY RespEmp;

SELECT DeptNo,
COUNT(ProjNo) AS NO_OF_PROJECTS
FROM PROJECT1
GROUP BY DeptNo;

SELECT ProjNo,
COUNT(EmpNo) AS NO_OF_EMPLOYEES
FROM EMP_PROJ1
GROUP BY ProjNo;

SELECT DeptNo,
COUNT(EmpNo) AS NO_OF_EMPLOYEES
FROM EMPLOYEE1
GROUP BY DeptNo
HAVING COUNT(EmpNo) > 3;

SELECT DeptNo,
ROUND(AVG(Salary), 2) AS AVERAGE_SALARY
FROM EMPLOYEE1
GROUP BY DeptNo
HAVING AVG(Salary) > 40000;


SELECT DeptNo,
SUM(Salary) AS TOTAL_SALARY
FROM EMPLOYEE1
GROUP BY DeptNo
HAVING SUM(Salary) > 200000;

SELECT Job,
COUNT(EmpNo) AS NO_OF_EMPLOYEES
FROM EMPLOYEE1
GROUP BY Job
HAVING COUNT(EmpNo) > 2;

SELECT EdLevel,
COUNT(EmpNo) AS NO_OF_EMPLOYEES
FROM EMPLOYEE1
GROUP BY EdLevel
HAVING COUNT(EmpNo) >= 5;

SELECT DeptNo,
MAX(Salary) AS MAX_SALARY
FROM EMPLOYEE1
GROUP BY DeptNo
HAVING MAX(Salary) > 60000;

SELECT DeptNo,
MIN(Salary) AS MIN_SALARY
FROM EMPLOYEE1
GROUP BY DeptNo
HAVING MIN(Salary) > 25000;

SELECT DeptNo,
ROUND(AVG(Bonus), 2) AS AVERAGE_BONUS
FROM EMPLOYEE1
GROUP BY DeptNo
HAVING AVG(Bonus) > 1000;

SELECT DeptNo,
COUNT(EmpNo) AS NO_OF_FEMALE_EMPLOYEES
FROM EMPLOYEE1
WHERE Gender = 'F'
GROUP BY DeptNo
HAVING COUNT(EmpNo) >= 2;

SELECT Job,
ROUND(AVG(Salary), 2) AS AVERAGE_SALARY
FROM EMPLOYEE1
GROUP BY Job
HAVING AVG(Salary) > 35000;

SELECT DeptNo,
COUNT(ProjNo) AS NO_OF_PROJECTS
FROM PROJECT1
GROUP BY DeptNo
HAVING COUNT(ProjNo) > 2;

SELECT RespEmp,
COUNT(ProjNo) AS NO_OF_PROJECTS
FROM PROJECT1
GROUP BY RespEmp
HAVING COUNT(ProjNo) > 1;

SELECT ProjNo,
COUNT(EmpNo) AS NO_OF_EMPLOYEES
FROM EMP_PROJ1
GROUP BY ProjNo
HAVING COUNT(EmpNo) > 3;

SELECT EmpNo,
COUNT(ProjNo) AS NO_OF_PROJECTS
FROM EMP_PROJ1
GROUP BY EmpNo
HAVING COUNT(ProjNo) > 1;

SELECT DeptNo,
COUNT(EmpNo) AS EMPLOYEE_COUNT,
SUM(Salary) AS TOTAL_SALARY,
ROUND(AVG(Salary), 2) AS AVERAGE_SALARY
FROM EMPLOYEE1
GROUP BY DeptNo
HAVING COUNT(EmpNo) > 3;


SELECT Job,
COUNT(EmpNo) AS EMPLOYEE_COUNT,
MAX(Salary) AS MAX_SALARY,
MIN(Salary) AS MIN_SALARY
FROM EMPLOYEE1
GROUP BY Job
HAVING AVG(Salary) > 35000;


SELECT DeptNo,
ROUND(AVG(Bonus), 2) AS AVERAGE_BONUS,
ROUND(AVG(Comm), 2) AS AVERAGE_COMMISSION
FROM EMPLOYEE1
GROUP BY DeptNo
HAVING AVG(Comm) > 3000;

SELECT EdLevel,
COUNT(EmpNo) AS EMPLOYEE_COUNT,
ROUND(AVG(Salary), 2) AS AVERAGE_SALARY
FROM EMPLOYEE1
GROUP BY EdLevel
HAVING AVG(Salary) > 40000;

SELECT Gender,
COUNT(EmpNo) AS EMPLOYEE_COUNT,
ROUND(AVG(Salary), 2) AS AVERAGE_SALARY,
SUM(Comm) AS TOTAL_COMMISSION
FROM EMPLOYEE1
GROUP BY Gender
HAVING AVG(Salary) > 35000;

SELECT DeptNo,
MAX(Salary) AS MAX_SALARY,
MIN(Salary) AS MIN_SALARY,
ROUND(AVG(Salary), 2) AS AVERAGE_SALARY
FROM EMPLOYEE1
GROUP BY DeptNo
HAVING COUNT(EmpNo) >= 2;
